# Use nginx as the base image
FROM nginx

# Copy the fake.html file to the default location
COPY fake.html /usr/share/nginx/html

# Set the hostname to fake.com
RUN echo "fake.com" > /etc/hostname

# Expose port 80 for internal communication
EXPOSE 80

# Start nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
